### ISSUE TITLE
Help: Nobara/Fedora: Installation 

### ISSUE THREAD

**Issue by SSUPD-Beast** [flafflar/panon#11]
**Desktop (please complete the following information):**
 - OS: Nobara / Fedora [e.g. ArchLinux or Ubuntu]
 - Version of Plasma 6 (Wayland)

**Describe the bug**

- file:///home/nobara/.local/share/plasma/plasmoids/panon/contents/ui/main.qml:11:28: Type Spectrum unavailable
- file:///home/nobara/.local/share/plasma/plasmoids/panon/contents/ui/Spectrum.qml:218:5: Type WsConnection unavailable
- file:///home/nobara/.local/share/plasma/plasmoids/panon/contents/ui/WsConnection.qml:2:1: module "QtWebSockets" is not installed

**Any error message shown in the console**
Please execute the following commands in the console and upload the outputs.

❯ git clone https://github.com/rbn42/panon.git
Cloning into 'panon'...
remote: Enumerating objects: 2701, done.
remote: Counting objects: 100% (228/228), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 2701 (delta 125), reused 196 (delta 115), pack-reused 2473 (from 1)
Receiving objects: 100% (2701/2701), 439.04 KiB | 2.14 MiB/s, done.
Resolving deltas: 100% (1566/1566), done.

❯ cd panon
panon on  stable 

❯ git submodule update --init
Submodule 'SoundCard' (https://github.com/bastibe/SoundCard) registered for path 'third_party/SoundCard'
Submodule 'hsluv-glsl' (https://github.com/williammalo/hsluv-glsl) registered for path 'third_party/hsluv-glsl'
Cloning into '/home/nobara/Downloads/panon/third_party/SoundCard'...
Cloning into '/home/nobara/Downloads/panon/third_party/hsluv-glsl'...
Submodule path 'third_party/SoundCard': checked out '745771575e56ab4c5ebf7118816e457c8e6b1b3d'
Submodule path 'third_party/hsluv-glsl': checked out '0ca50ad85bd879f2f71bcfda2adaa98049aaaa50'

- You need to install plasma-sdk to get plasmoidviewer. 
Installed: _plasma-sdk-6.1.4-1.fc40.x86_64 - Complete!_

❯ plasmoidviewer --applet ./plasmoid/
QML debugging is enabled. Only use this in a safe environment.
kf.plasma.quick: Applet preload policy set to 1
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:195:25: QML FolderViewDropArea (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
Toolbox not loading, toolbox package is either invalid or disabled.
QQmlComponent: Component is not ready
kf.plasma.quick: error when loading applet "panon" QList("This Widget was written for an unknown older version of Plasma and is not compatible with Plasma 6. Please contact the widget's author for an updated version.")
qt.svg.draw: The requested buffer size is too big, ignoring
qt.svg.draw: The requested filter is too big, ignoring
qt.svg.draw: The requested buffer size is too big, ignoring
qt.svg.draw: The requested buffer size is too big, ignoring
qt.svg.draw: The requested buffer size is too big, ignoring
qt.svg.draw: The requested buffer size is too big, ignoring
qt.svg.draw: The requested buffer size is too big, ignoring

**Comment by flafflar** [comment]
I think you might have cloned the old repository? I haven't updated the issue template yet. Please follow the installation instructions in the README and see if the problem persists.

**Comment by SSUPD-Beast** [comment]
I've downloaded latest 6.0.1 widget and followed the instructions on my Arch install (it works on Arch) 
However, this issue i opened up is for Nobara/Fedora installation. I dont see any instructions for Fedora/Nobara in README. I'm pretty sure i'm missing dependencies on my Nobara/Fedora.

**Comment by SSUPD-Beast** [comment]
Shout to "rustynail" and others in Nobara/Proton-GE community.
I was able to download correct dependencies. Thank you for developing crew of this widget (i've been looking for something like this for long time.

**Installation for Fedora/Nobara**
**Step-1**: Download Dependencies
`sudo dnf install qt6-qtwebsockets-devel qt6-qtshadertools-devel python3-docopt python3-numpy python3-pyaudio python3-websockets`

**Step-2**: git clone your repo.
**Step-3**: `cd panon`
**Step-3**: `./makepackage.sh`
**Step-4**: Install "panon.plasmoid"

and be mesmerized in this sound visualization.

Thanks you!

Not sure if there's something else needs to be done to for "extra-downloaded" effects to work. 
I've downloaded couple but they dont seem to work.

**Comment by flafflar** [comment]
Glad to hear it! I've added the installation instructions for Nobara in the README.

> Not sure if there's something else needs to be done to for "extra-downloaded" effects to work.
> I've downloaded couple but they dont seem to work.

This is a known issue, see #8 for more information.
