### ISSUE TITLE
[Feature request] Please update installation instruction.

### ISSUE THREAD

**Issue by oberkut** [flafflar/panon#2]
Please update Installation Instruction for kde 6. 
On openSUSE Tumbleweed plasmoid not working.

**Comment by flafflar** [comment]
Can you provide some more information? What exactly is it that doesn't work? Maybe attach some logs

**Comment by oberkut** [comment]
file:///home/berkut/.local/share/plasma/plasmoids/panon/contents/ui/main.qml:11:28: Type Spectrum unavailable

file:///home/berkut/.local/share/plasma/plasmoids/panon/contents/ui/Spectrum.qml:218:5: Type WsConnection unavailable

file:///home/berkut/.local/share/plasma/plasmoids/panon/contents/ui/WsConnection.qml:2:1: module "QtWebSockets" is not installed

**Comment by ruinivist** [comment]
@oberkut works for me

![image](https://github.com/user-attachments/assets/fec2fd6b-249a-4196-b557-c78cd0accbc0)

Nothing out of the ordinary
- clone
- `git submodule update --init`
- then install `python-docopt python-numpy python-pyaudio python-cffi python-websockets qt6-websockets`
- then settings audio backend -> pulseaudio (others didn't work for me) -> monitor of current device
- also ensured I had `qsb` in `/usr/lib/qt6/bin`

For your case, I think `qt6-websockets` is the issue

**Comment by flafflar** [comment]
@oberkut, I updated the installation instructions in the README. I tested them in a fresh install of OpenSUSE and work fine. If you still have a problem, please reopen this issue.
