### ISSUE TITLE
[BUG] [minor] All configuration inputs disabled when opening config UI

### ISSUE THREAD

**Issue by Doridian** [flafflar/panon#4]
**Desktop (please complete the following information):**
 - OS: Arch
 - Plasma 6.1.4

**Describe the bug**
When using Panon on my KDE installation, for some reason all controls of the config UI are disabled until I go to the "About" tab and then back.
Sadly, this does not happen with `plasmoidviewer`, but I could get the logs out of the journal. Attached here  are the burst of logs that happens when I click "Configure panon" in the right-click menu.

A lot of these warnings are probably nothing, because they also happen in plasmoidviewer, where this does not happen.
[logs.txt](https://github.com/user-attachments/files/16698668/x.txt)

Screenshot below shows the problem.
![Screenshot_20240821_135356](https://github.com/user-attachments/assets/d4613604-3b4d-4720-85d7-c00f7e9390c9)

Marking as minor because if I click of the easy workaround

**Comment by flafflar** [comment]
It works for now, but the hack is kind of temporary and might break again in the future.

Also @Doridian what theme are you using? It seems very pretty

**Comment by Doridian** [comment]
> Also @Doridian what theme are you using? It seems very pretty

Thanks! (both for the hack and the compliment)

A combination of the theme `shades-of-purple` with the accent color changed from its default yellow to purple, and `candy-icons` for the icons (both are in the KDE store)
