### ISSUE TITLE
[Feature request] {Background transparency} 

### ISSUE THREAD

**Issue by G-grbz** [flafflar/panon#6]
There is no setting for the background to be transparent. Thank you for your effort.

**Comment by flafflar** [comment]
I have added it in [v6.0.1](https://github.com/flafflar/panon/releases/tag/v6.0.1). 

You can enable it by entering edit mode and clicking on the *"Hide background"* button:
![Screenshot_20240901_180701](https://github.com/user-attachments/assets/71fdf1fd-b04b-4757-a26b-085581de1956)
