### ISSUE TITLE
[BUG] Not work on Wayland

### ISSUE THREAD

**Issue by oberkut** [flafflar/panon#7]
- OS: openSUSE Tumbleweed
 - 6.1.4

Plasmoid not work on wayland (X11 work correctly)

plasmoidviewer --applet panon
output:
Failed to build graphics pipeline state.

**Comment by flafflar** [comment]
I can't seem to reproduce it. What graphics card do you have?

**Comment by oberkut** [comment]
Nvidia GTX 960.
Nvidia driver 550

**Comment by flafflar** [comment]
Apparently there is an issue with the OpenGL implementation in tht specific version of the driver (see [this comment](https://forum.zorin.com/t/the-game-does-not-run-on-the-nvidia-550-driver/36507/7)). This might cause the shaders to not load properly. Try downgrading your drivers and see if the issue persists.

**Comment by oberkut** [comment]
Yesterday the video driver was updated to version 550.107.02 and everything worked. Fixed.

**Comment by OptixWolf** [comment]
Im facing the same Issue on my Computer
The Issue is only when using Wayland / Proprietary Nvidia Drivers

OS: Arch Linux (Also tested on Fedora 41)
Framework: 6.8.0

Nvidia Drivers: 565.57.01
Graphics card: Nvidia GeForce GTX 1080 Ti

output: Failed to build graphics pipeline state.
