### ISSUE TITLE
[BUG] Can't seem to get it working on Fedora Kinoite 40

### ISSUE THREAD

**Issue by zastrixarundell** [flafflar/panon#9]
**Desktop (please complete the following information):**
 - OS: Fedora Kinoite 40
 - Version of Plasma Framework: 6.5.0

**Describe the bug**
I was able to *start* the plasmoid by installing `qt6-qtwebsockets-devel` onto my system and rebooting but now I get this issue:

![image](https://github.com/user-attachments/assets/44da7155-42e0-423d-8e77-3b8301927cf0)

Doesn't matter which visual effect I use. 

**Any error message shown in the console**
```bash
Sep 07 00:16:46 main-pc plasmashell[5444]: file:///var/home/zastrix/.local/share/plasma/plasmoids/panon/contents/ui/main.qml:9:5: Unable to assign [undefined] to QQmlComponent*
Sep 07 00:16:46 main-pc plasmashell[5444]: file:///var/home/zastrix/.local/share/plasma/plasmoids/panon/contents/ui/main.qml:9:5: Unable to assign [undefined] to QQmlComponent*
Sep 07 00:16:46 main-pc plasmashell[5444]: file:///var/home/zastrix/.local/share/plasma/plasmoids/panon/contents/ui/Spectrum.qml:184: TypeError: Cannot read property 'textColor' of undefined
Sep 07 00:16:46 main-pc plasmashell[5444]: file:///var/home/zastrix/.local/share/plasma/plasmoids/panon/contents/ui/Spectrum.qml:95:45: QML QQuickImage: Cannot open file:///: Path is a directory
```

**Comment by zastrixarundell** [comment]
AMD cpu and AMD gpu, wayland setup

**Comment by zastrixarundell** [comment]
Not as bug -- just had to add these dependencies to my system: `python3-docopt python3-numpy python3-pyaudio python3-websockets qt6-qtwebsockets-devel`.

**Comment by flafflar** [comment]
@zastrixarundell can you send exactly what command you used? I want to include it in the README

**Comment by zastrixarundell** [comment]
@flafflar

```bash
sudo dnf in python3-docopt python3-numpy python3-pyaudio python3-websockets qt6-qtwebsockets-devel
```

Although I'll check if `qt6-qtwebsockets-devel` is actually needed. 

Edit:

I do use an immutable system so instead of `sudo dnf in` it was `rpm-ostree install`, which is the same thing *basically*.

**Comment by zastrixarundell** [comment]
@flafflar yeah looks like `qt6-qtwebsockets-devel` is needed.
